export const routes = {
  home: '/',
  products: '/products',
  product: '/products/:id',
  promotions: '/promotions',
  contact: '/contact',
  login: '/signin',
  register: '/register',
  cart: '/cart/:id?',
  shipping: '/shipping',
  payment: '/payment',
  placeOrder: '/placeorder',
  order: '/order/:id',
  orderHistory: '/orderhistory',
  profile: '/profile',
  adminProducts: '/productlist',
  editProduct: '/products/:id/edit',
  adminOrder: '/orderList',
  adminUsers: '/userlist',
  adminEditUser: '/user/:id/edit',
};
